import type { Metadata } from "next"
import { Noto_Sans as Font } from "next/font/google"

import Navbar from "@/components/navbar"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const font = Font({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${font.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
